server:
  port: 8080

spring:
  datasource:
    schema: sicoem
    url: jdbc:postgresql://localhost:5432/dev_sicoem_db
    username: userdevsicoem
    password: .user_Dev.
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: sicoem
  flyway:
    schema: sicoem
    locations: classpath:db/migration,classpath:dev/db/migration
